version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
      args: 
        NODE_ENV: development
    container_name: node_app_dev
    volumes:
      - ./:/app:ro
      - /app/node_modules
    env_file:
      - ./env/.dev.env
    ports:
      - 3000:4000
    command: npm run dev
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml down -v
# docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d --build
